# Generated by Django 2.2.3 on 2020-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200131_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.FloatField(default=0),
        ),
    ]
