# Generated by Django 2.2.3 on 2020-02-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_category_slud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slud',
            new_name='slug',
        ),
    ]
